"""Initial migration: create users, universities, courses, career_paths tables

Revision ID: 778e3cf11d90
Revises: 
Create Date: 2025-12-09 20:59:42.476372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778e3cf11d90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_career_paths_id', table_name='career_paths')
    op.drop_index('ix_career_paths_name', table_name='career_paths')
    op.drop_table('career_paths')
    op.drop_index('ix_universities_country', table_name='universities')
    op.drop_index('ix_universities_id', table_name='universities')
    op.drop_index('ix_universities_name', table_name='universities')
    op.drop_table('universities')
    op.drop_index('ix_courses_id', table_name='courses')
    op.drop_index('ix_courses_name', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('duration', sa.VARCHAR(), nullable=True),
    sa.Column('degree_type', sa.VARCHAR(), nullable=True),
    sa.Column('university_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courses_name', 'courses', ['name'], unique=False)
    op.create_index('ix_courses_id', 'courses', ['id'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('country', sa.VARCHAR(), nullable=True),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('ranking', sa.INTEGER(), nullable=True),
    sa.Column('website', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_universities_name', 'universities', ['name'], unique=False)
    op.create_index('ix_universities_id', 'universities', ['id'], unique=False)
    op.create_index('ix_universities_country', 'universities', ['country'], unique=False)
    op.create_table('career_paths',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('avg_salary', sa.VARCHAR(), nullable=True),
    sa.Column('growth_rate', sa.VARCHAR(), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_career_paths_name', 'career_paths', ['name'], unique=False)
    op.create_index('ix_career_paths_id', 'career_paths', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
